POST https://auth.sh0.su/realms/text-vision/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=admin-cli&client_secret=pEghjIsJDKVWxZMfFb2uN4ZGyhl6jsxT